# Create expected runtime dirs at boot (instead of baking them into the image)
d /var/crash                                   0755 root root -
d /var/lib/AccountsService                     0775 root root -
d /var/lib/AccountsService/icons               0775 root root -
d /var/lib/AccountsService/users               0700 root root -
d /var/lib/abrt                                0755 root root -
# Add more lines here if lint shows additional /var dirs you keep wiping at build time
