# Use "-" for values you don't want to set explicitly
u abrt           -  "ABRT service user"          - -
g abrt           -  -                             - -
u nm-openconnect -  "NM OpenConnect user"         - -
g nm-openconnect -  -                             - -
u nm-openvpn     -  "NM OpenVPN user"             - -
g nm-openvpn     -  -                             - -
u wsdd           -  "WS-Discovery service user"   - -
g wsdd           -  -                             - -
